name: expense_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #  Firebase services
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  google_sign_in: ^6.0.2

  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9

  get: ^4.6.6
  flutter_svg: ^2.0.9
  logger: ^2.0.2+1
  fluttertoast: ^8.2.4
  country_codes: ^2.2.0
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.9
  flutter_share: ^2.0.0
  in_app_review: ^2.0.8
  convex_bottom_bar: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#3389FF"
  color_dark: "#272727"
  image: assets/icons/misc/JustSplit_logo_v3-08.svg
  image_dark: assets/icons/misc/JustSplit_logo_v3-08.svg

  android_12:
    icon_background_color: "#3389FF"
    image: assets/icons/misc/JustSplit_logo_v3-08.svg
    icon_background_color_dark: "#272727"
    image_dark: assets/icons/misc/JustSplit_logo_v3-08.svg



flutter:
  uses-material-design: true
  assets:
    - assets/icons/auth_icons/
    - assets/icons/nav_bar/
    - assets/icons/bottom_bar/
    - assets/icons/misc/
    - assets/icons/drawer_menu/
    - assets/flare/
    - assets/illustrations/
    - assets/images/
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600





























